### ISSUE TITLE
uft8 - russian and others special caracters

### ISSUE THREAD

**Issue by optimum-dulopin** [enriclluelles/route_translator#22]
Hi,

thanks for this great tool, it save me lot of time. But unfortunatly Im stuck because special caracters are not recognized. 
for instance for page /ru/войти , I have this error message
No route matches [GET] "/ru/%D0%B2%D0%BE%D0%B9%D1%82%D0%B8"

same for french special caracters like "è" . for /fr/dernière , 
No route matches [GET] "/fr/derni%C3%A8re" 

but if I change in i18n-routes.yml to derniere, /fr/derniere is working fine. 

if this caracters are inside variable, it is working well
for instance if my route is like 'derniere-:myvar'
if I go to page /fr/derniere-première
it is working well and I have params[:myvar] = "première"

Is there anythink  I can do to make it works ?

thanks

PS : rake routes give me the right routes

PS 2 : on google, I found that this used to be a bug on rails, bug it is said to be fixed, they add Rack::Utils.escape so that we dont have to do it manually on routes.rb. In  actionpack/lib/action_dispatch/routing/mapper.rb, they do
mapping = Mapping.new(@set, @scope, URI.parser.escape(path), options) , maybe it can help ;-)
Im using rails 3.2.13

**Comment by optimum-dulopin** [comment]
hi, I report this issues few years ago, then it was fixed, but with last version it doesnt work anymore

**Comment by tagliala** [comment]
@optimum-dulopin it works fine on 4.2.* but it doesn't work on 4.3.0? Could you please clarify?

The test case added for this issue is still passing: https://github.com/enriclluelles/route_translator/blob/2e1b29f213c62df00b0ca4cb73839cbfcac5a4c3/test/routing_test.rb#L104

**Comment by optimum-dulopin** [comment]
yes exactly, 4.2.5 is ok, but with 4.3.0 I have No route matches [GET] . Maybe problem is different than before, but result is same

**Comment by optimum-dulopin** [comment]
right,problem is actually different, and it seems that it was also a problem before. Just it was working for well for me because I had override translations_for in an initializer. I will investigate and let u know when I will have more info

**Comment by optimum-dulopin** [comment]
is there a way to debug ? byebug doesn't seems to work inside function

**Comment by tagliala** [comment]
@optimum-dulopin thanks!

Please start a new issue as soon as you have a reproducible test case
